### ISSUE TITLE
Source code and instructions to flash

### ISSUE THREAD

**Issue by r1ckr** [SeeedJP/ReButton#1]
Hey guys, I've just got one of the ReButton and got it connected to Azure. Would you upload the source code and instructions on how to flash it? Thanks

**Comment by ytsuboi** [comment]
Hi @r1ckr 
We are currently working on publishing source code of default firmware, since we need to migrate the source code for ReButton with the code for AZ3166 it may take sometime.

**Comment by matsujirushi** [comment]
Source code was published.
https://github.com/SeeedJP/ReButtonApp

**Comment by matsujirushi** [comment]
Source code is [here](https://github.com/SeeedJP/ReButtonApp).
Instrunction is Firmware Development section in [here](https://seeedjp.github.io/ReButton/).
