### ISSUE TITLE
How can I get access to the button click type in Azure IoT Central?

### ISSUE THREAD

**Issue by niels9001** [SeeedJP/ReButton#10]
I have configured by Azure IoT Central instance so it connects to the ReButton.

However, when I set up a Rule I cannot use the State (e.g. Single click vs. Double click) as a Rule. For instance, single click -> email person A vs. double click -> email person B.

How can this be configured?

Regards,
Niels

**Comment by matsujirushi** [comment]
Hi,
That is Azure IoT Central functions. We cannot provide best answer.
I think maybe you can do this.
1. Add 'actionNum' field to Telemetry.
2. Add Rule of Telemetry with condition.

Please try it.

**Comment by matsujirushi** [comment]
FYI
[MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azureiothub)

**Comment by cadocomp** [comment]
I am having this exact same issue as well. Cannot generate alert in IOT Central, even when adding 'actionNum' as a Telemetry field.

**Comment by matsujirushi** [comment]
Hi,
ReButton looks fine.
![image](https://user-images.githubusercontent.com/8079404/59648213-3a9f3380-91b9-11e9-9e83-5a02c8e5d223.png)

Rule is IoT Central function.
Please ask [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=azureiothub).
