### ISSUE TITLE
Not seeing reported values in Azure IoT Device Twin

### ISSUE THREAD

**Issue by bradboren** [SeeedJP/ReButton#13]
I purchased a ReButton and connected to WiFi and my IoT Hub device (using section 3.1 of the instructions).  When I press the button it connects to the WiFi and seems to send a message to Azure IoT.

When I look at my device twin I expect to see actionNum and message values in the reported section.  Instead I see:

"reported": {
      "customMessageEnable": {
        "value": false
      },
      "$metadata": {
        "$lastUpdated": "2019-08-09T19:28:25.0391204Z",
        "customMessageEnable": {
          "$lastUpdated": "2019-08-09T19:28:25.0391204Z",
          "value": {
            "$lastUpdated": "2019-08-09T19:28:25.0391204Z"
          }
        }
      },
      "$version": 14
    }

The date/time seems to update in the $lastUpdated but no other info.  Any suggestions on what I might be doing wrong?  I am excited to get this working. 

Thank you!

**Comment by matsujirushi** [comment]
Hi @bradboren ,
ReButton update the reported properties is customMessageEnable only. [code](https://github.com/SeeedJP/ReButton/tree/master/firmware)
So actionNum and message value is into D2C message. [code](https://github.com/SeeedJP/ReButtonApp/blob/master/ActionSendMessage.cpp#L65-L66)

**Comment by bradboren** [comment]
Thank you for the reply!  Are you saying that I need to update the firmware?  I have not since I received the rebutton.  Or are you saying that I need to edit the code used in the ReButton?  I was hoping to avoid that and have a more plug and play type of device.

Thank you again for the assistance.

**Comment by bradboren** [comment]
I think I am getting it now.

The Rebutton will only have a "customMessageEnabled" value in the reported properties (which is stored in the device twin).  The D2C message that is sent (and not shown in the Device Twin) is where the actionNum and other message data is sent.

That is a bit of a challenge on my side as my tool is looking at device twin info.  But I think I understand better what is happening.

Thank you again for the help!  I still hope this works but need to turn to some of our developers to see if we can consume the message data.
