### ISSUE TITLE
Add message properties for routing

### ISSUE THREAD

**Issue by hugovoerman** [SeeedJP/ReButton#2]
Hi Guys,

I got the ReButton to connect to IoT Hub, quite easily. In order to route/detect the messages from the ReButton a message property would come in handy. One could use this message property to route the messages to a special "ReButton" endpoint, or filter them out in ASA, or whatever. Filtering on the payload is way to risky, as messages from several devices may contain the same field(s).

Best regards,

Hugo

p.s.: I am also looking forward to the sourcecode of the firmware. With that I could have implemented the above myself.

**Comment by matsujirushi** [comment]
Hi @hugovoerman ,

1. Oh I got it.
In the next version, I will add a message property at message.
Please keep open this issue.

2. We are currently working on publishing source code of default firmware. #1

**Comment by hugovoerman** [comment]
Hi Takashi,

Thank you for the email.

Please make this property configurable.

Best regards,
Hugo Voerman



Sent from my phone
On Takashi Matsuoka <notifications@github.com>, 25 okt. 2018 3:35 AM wrote:

Hi @hugovoerman<https://github.com/hugovoerman> ,

  1.  Oh I got it.
In the next version, I will add a message property at message.
Please keep open this issue.

  2.  We are currently working on publishing source code of default firmware. #1<https://github.com/SeeedJP/ReButton/issues/1>

**Comment by matsujirushi** [comment]
FYI
https://github.com/SeeedJP/ReButtonApp/blob/master/ReButtonClient.cpp#L235
https://github.com/SeeedJP/ReButton/tree/master/firmware

**Comment by matsujirushi** [comment]
Released. (in v1.1)
https://github.com/SeeedJP/ReButton/blob/master/firmware/readme.md
