### ISSUE TITLE
Unable to install Rebutton board pack in Arudino IDE

### ISSUE THREAD

**Issue by homemadestea58** [SeeedJP/ReButton#20]
System:
- Ubuntu 20.04 running in WSL (Windows Subsystem for Linux)
- Arduino IDE 2.0.4
- Host: Lenovo AMD Ryzen 5500U

Issue:
I am not able to install the SeedJP ReButton Board package in my Arduino IDE. Each time I try to install it, the IDE throws this error:
`Error: 13 INTERNAL: Cannot install tool SeeedJP:arm-none-eabi-gcc@5_4-2016q3-seeed: testing local archive integrity: testing archive size: fetched archive size differs from size specified in index: 51395093 != 0`

I have managed to install the Pack on my Windows PC directly, but both my Raspberry Pi and Ubuntu WSL have thrown this error.

Does anyone know how to fix this, or even how to install the packages manually?

Logs:
`Downloading packages
SeeedJP:arm-none-eabi-gcc@5_4-2016q3-seeed
SeeedJP:openocd@0.11.0-1-xpack
SeeedJP:SeeedJP_ReButton@2.1
Installing SeeedJP:arm-none-eabi-gcc@5_4-2016q3-seeed
Failed to install platform: SeeedJP:SeeedJP_ReButton.
Error: 13 INTERNAL: Cannot install tool SeeedJP:arm-none-eabi-gcc@5_4-2016q3-seeed: testing local archive integrity: testing archive size: fetched archive size differs from size specified in index: 51395093 != 0`

My aim is to try and replace the Azure code with a simple HTTP request to my local Home Assistant instance so any help on that would also be appreciated.

**Comment by matsujirushi** [comment]
Thank you for the report.

I fixed `https://www.seeed.co.jp/package_SeeedJP_index.json`. You can download and install the ReButton platform on Linux.
However, it has been confirmed that some compilation problems occur.

We compile ReButton's firmware in Windows environment. Therefore, it is strongly recommended to use the Windows environment.

**Comment by homemadestea58** [comment]
@matsujirushi Thank you for that. 
I also wanted to ask, if I want to change the ReButton to use simple http requests instead of Azure for each button click, eg. for Home Assistant, what network library would I use? 

Would I just use one of the built in Arduino ones, the ones in the IDE, or do I use something else like Winsock2?

**Comment by matsujirushi** [comment]
@homemadestea58 
I created new issue. #22
