### ISSUE TITLE
to use simple http requests

### ISSUE THREAD

**Issue by matsujirushi** [SeeedJP/ReButton#22]
I also wanted to ask, if I want to change the ReButton to use simple http requests instead of Azure for each button click, eg. for Home Assistant, what network library would I use? 

Would I just use one of the built in Arduino ones, the ones in the IDE, or do I use something else like Winsock2?

_Originally posted by @homemadestea58 in https://github.com/SeeedJP/ReButton/issues/20#issuecomment-1510584996_

**Comment by matsujirushi** [comment]
The ReButton platform is based on the [AZ3166 IoT DevKit platform](https://github.com/microsoft/devkit-sdk).
I think you can use the HTTPClient class.

https://microsoft.github.io/azure-iot-developer-kit/docs/apis/http-client/

**Comment by homemadestea58** [comment]
Thanks @matsujirushi. I'll check this out.
