### ISSUE TITLE
Missed by a Mile

### ISSUE THREAD

**Issue by timkay** [SeeedJP/ReButton#3]
I got a free Re-Button at the IoT in Action show today. I followed the directions to make it work, got hung up in a few places, and concluded NO WAY! The initial configuration needed to get this thing to do *anything* is way, way too complicated. I'll suspect that almost nobody with a free button from the show is going to manage to get it working.

Before I start my rant, I should mention my background, to let you know I'm not some inexperienced user. I have a Ph.D. in Computer Science. I have been using AWS for more than a decade. I wrote the first popular command line tool for AWS, back when Amazon expected you to write your own code to do every bit of configuration. I recently have been using GCP successfully. I've never used Azure.

The fact that I've never used Azure shouldn't disqualify me from trying the ReButton, unless the project targets only people who have experience with Azure IoT. In concept, lots of people should be able to find ReButton really useful. I don't think they will.

Here is a list of observations/issues:

* It's easy enough to get it into AP mode. My desktop is hard wired, so I can't use it to configure the button. Instead I used my Android phone.
* The button serves pages that render terribly on a phone. They maintain 1-inch margins, which leaves about 1/2 inch  down the middle of the screen for content.
* I entered my WiFi credentials as instructed then Shutdown. The button blinks a blue pattern (not documented) then blinks red, which strikes me as an error, but again not documented.
* The instructions say to put the IoT Device Connection String in the appropriate place. They don't say if I need to go back into AP mode to do that. Do I, or can I connect to the ReButton while it's connected to my WiFi? I couldn't find the device on my WiFi, probably because it turns off quickly. I added the string via AP mode, and they seem to stick.
* It's hard to do these configurations now: The device turns off very quickly after entering AP mode. (Blinks white for a while then off, before I have a chance to connect my phone and do the configuration.)
* I followed the instructions to create Azure IoT Hub + IoT Device. The instructions skipped over a few important steps, such as creating a Hub before you can create a Device. And be careful: the default choice for creating a Hub comes with a $25/mo charge, whereas there is a free option that you can choose.
* The instructions mention "Azure IoT Hub" and "Azure IoT Central". Do I need to do both? Or are they two alternative ways to configure? I suspect it's two different ones, but the instructions don't say so.
* I managed to create a Hub and a Device. I got the Connection String into the device. But that's as far as I got. Do I need to do the Central thing too? Or can I get some activity using just IoT Hub? I started to do a tutorial that talks me through how to use Hub, but I didn't get very far. It's *way* too much of a commitment at this stage of evaluating the ReButton.

At this point, realizing I'd need another hour or two, I deleted my storage and hub and then closed the Azure window.

Seriously?

If you want to have a wider audience reach some measure of success, they need to have a successful experience after adding WiFi credentials. Maybe have the devices talk to some pre-configured service by default. I would enter my WiFi credentials, then go to rebutton.com, type in a serial number, and then see my device doing something.

I could build that for you. Let me know if you are interested.

**Comment by ytsuboi** [comment]
@timkay Thank you for your feedback! It helps us to see where we need to improve.

**Comment by Hi007** [comment]
Hi there,
I'll echo some of my observations that the instructions require some work. I haven't been successful in configuring the ReButton.
I see that configuring the REButton through AP mode to Wifi is easy. After that using the IoT Hub or IoT  central are the choices. I wanted to use IoT hub the instruction in 3.1 stops at sticking in the IoT hub connection string. It does not mention how to create the Device in IoT Hub.
And finally some info on testing would be useful.

Will be happy to help test the instructions so that they are helpful.
