### ISSUE TITLE
OTA update failed

### ISSUE THREAD

**Issue by tommywu052** [SeeedJP/ReButton#5]
Package URI: https://1drv.ms/u/s!AormijBthQPvg4U-20F3bHj5fGEmPg
Package CRC: 170c
Package Size :626

When I try to flash the firmware through update as above , it always complains 
File /ubus not_found and redirect to 192.168.0.1/firmware2 . 

What should I fill in the correct parameters ?

**Comment by matsujirushi** [comment]
Hi tommywu052,
I checked to download firmware on BLOB storage on Azure. like [this](https://github.com/Microsoft/vscode-iot-workbench/blob/master/docs/iot-devkit/devkit-ota.md#upload-the-firmware-to-cloud).
Firmware update function use HTTPClient() in OTADownloadFirmware(). It not support download on OneDrive.

**Comment by tommywu052** [comment]
Thanks for the info.  Beside change to Azure blob, you also have to  prefix:0x before the generated CRC value like :
fwPath: xxxxxx\ReButtonApp101.bin
fwPackageCheckValue: **0x**6f62
fwSize: 641796

**Comment by matsujirushi** [comment]
Thanks for your feedback.
