### ISSUE TITLE
Seeed ReButton doesn't go into Wifi AP mode

### ISSUE THREAD

**Issue by Robbo1976** [SeeedJP/ReButton#7]
I'm a newbie, so hope I'm in the right location to ask this question: I received a Seeed Rebutton at IOT event recently and trying to connect to it via Wifi. Unfortunately the button doesn't boot into AP mode. Instructions say 'Hold button until RGB LED turns into White. RGB LED will start with Blue, Yellow, Cyan, then White. This will take about 10 seconds. Then: 
Release button and confirm ReButton is in AP mode. When ReButton successfully boots into AP Mode, RGB LED will blink in White.  I do get the 'white' LED, then let the button go, it flashes twice, but doesn't seems to boot in AP mode, nor show the AZB-..... Access point. Any tips? Can't find it on Seeed website or googling it. Is there anyway to rest the device? There's only 1 jumper on the button, on the left pin and not connected to the right pin. If I connect the jumper to both pins the LED starts flashing orange, but no AP ....   Thanks for your help,

**Comment by matsujirushi** [comment]
Hi,
You don't need to connect jumper.
Can you see that LED changing BLUE->YELLOW->CYAN->WHITE?
https://youtu.be/EZWZbriy8e4?t=1715

**Comment by Robbo1976** [comment]
Hi Takashi, thanks for your reply.
It is changing color but the white is not really white, but that’s the 4th color, then letting go of the button I see it flash twice, but no Wifi AP appears on my phone or on my laptop, so it doesn’t seem to go into AP mode.
In your video, I can clearly see the LED continues to flash white, where mine only flashes twice and then stops, so it doesn't go into AP mode.
Maybe my Seeed button is different (cover is also blue instead of green, but that could be just cosmetic).

Thanks for your help.

Attachments area

![image_6546160](https://user-images.githubusercontent.com/48938107/54992890-97ed7380-5014-11e9-9d91-965010520395.JPG)

**Comment by matsujirushi** [comment]
Hi,
I checked.
ReButton need 3V/400mA from battery to go to AP mode.
Could you change to new battery?

**Comment by Robbo1976** [comment]
Brilliant, that was the solution, I never thought of that as the LEDs were
responding.
After changing the battery with brand new ones, the access point enables
and I can connect and configure the button.
What use cases have you come across for the button?

Thanks,
Robin
