### ISSUE TITLE
Please describe purpose of jumper

### ISSUE THREAD

**Issue by JuergenKosel** [SeeedJP/ReButton#8]
Hello,

please describe the purpose of the jumper.

**Comment by matsujirushi** [comment]
Hi,

Jumper has two functions.
1. ReButton keep power supply on. It use when firmware development.
2. Reset parameters (by default firmware). 
  https://github.com/SeeedJP/ReButtonApp/blob/master/ReButtonApp.ino#L36
  https://github.com/SeeedJP/ReButtonApp/blob/master/Config.cpp#L34
