### ISSUE TITLE
[Newbie] Question about click velocity

### ISSUE THREAD

**Issue by Defkon1** [SeeedJP/ReButton#9]
Hello everybody!
I configured my ReButton to send D2C to IoT Hub and set VSCode listening to the message queue.

If I click the button nothing happens (neither if I double click or triple click); if I keep pressed for at least 1 second the click is performed.

Is this the intended behaviour (more sort of a short-press rather than a click)?

**Comment by Defkon1** [comment]
Probably I found the reason by myself in RebuttonApp/Input.cpp source file:

`static const int InputWaitForClickTime   = 1000;  // [msec.]`

should I lower the first one and reflash the ReButton to achieve a faster click recognition, right?

**Comment by ytsuboi** [comment]
Hi @Defkon1,
The button pressing start supplying power to the electronics and starts running code. About 0.3 sec after MCU start running, MCU start to keep the power turned on. This means, if you take your finger off in this 0.3 sec, MCU can't start keeping the power supply and power will be shut off.
So, please press/click and hold the button for more than 0.5 sec.

**Comment by Defkon1** [comment]
thanks for the clarification!
